-- Local-only seed data, applied by `supabase db reset`.
-- Deliberately empty: identity-bearing fixtures (a draft event with
-- participants) need `auth.users` rows, which requires the Supabase Admin
-- API, not plain SQL. Run `pnpm --filter db seed` after resetting instead
-- (see openspec/changes/data-model-rls/design.md D7).
